### PR TITLE
Implement stringified NBT (sNBT)

### LINKED ISSUE #49: Support stringified NBT (sNBT)
Minecraft also uses a variant of NBT that is human-readable and json-like.

If this crate/set of crates wants to be complete, it should offer serde support for this format too.

The (de)serializers would have to agree on the format of the array types to be compatible.

### PR DESCRIPTION
**Pull request by GrizzlT**
First commit in this draft to implement sNBT.

Tasks:
- [x] Implement serializer
    - [x] resolve todo's in the code
- [x] Unit test serializer
- [x] Implement deserializer
- [x] Unit test deserializer

I went ahead and removed the `cesu8` and `flate2` dependencies. I also suspect that `fastnbt` will turn into a `dev-dependency` used for testing only.

### CODE REVIEW

**Comment by GrizzlT** [comment]
Currently there's a few `TODO` comments that I'm not sure about what to do with. NBT arrays still need to receive support.

**Comment by GrizzlT** [comment]
The `TODO`s in the `Serializer` are still there. The deserializer is now fully implemented and does not support complex enums. `fastnbt` is now a dev-dependency and `nom` was used for parsing the input string.

Feel free to add tests and/or add suggestions.

**Comment by owengage** [comment]
This looks great. Are you wanting to merge this PR and do the rest in another, or just keep going in this one?

**Comment by GrizzlT** [comment]
I would like to resolve the TODOs left before merging.

It's mostly just needing confirmation whether the serializer is allowed to error like `fastnbt` or if we should do something else.

Merging into the main branch can happen in a different PR.

**Comment by owengage** [comment]
For the TODOs about panic vs error when something cannot be serialized, I do think they should error. Panics feel extreme. That said it's hard to imagine it not signalling a bug in the program.

[The convention](https://serde.rs/conventions.html) for erroring is that serialize and deserialize share the same error.

**Comment by GrizzlT** [comment]
In that case, I'm happy with this so far, feel free to merge upstream!

**Comment by GrizzlT** [comment]
@owengage any updates?

**Comment by owengage** [comment]
Hi @GrizzlT, sorry I didn't realise you were ready to merge. Is there anything left to do from your perspective here? At some point I'll have a serious look over the code and look to merge to master. Been relatively busy as of late!

**Comment by GrizzlT** [comment]
@owengage Thanks for merging!

My leftover concerns have been mostly described in #85 to improve overall performance. If I have some time again I'll look at that myself but it would need changes in both `fastnbt` and `fastsnbt`. Other than that I think there are no current issues holding snbt back from being merged into master (the performance increase is only an internal change).

I'll definitely be able to use this branch for now, awesome!

**Pull request merged**
